CREATE TABLE `products` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(100) DEFAULT NULL,
  `Price` DECIMAL(10, 2) DEFAULT NULL,
  `StockQuantity` INT DEFAULT NULL,
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;